version: "3.3"

services:
  postgres:
    container_name: sbs_postgres
    image: "postgres:13.3"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: product-service-db
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - spring-boot-simple
      
  app:
    container_name: product-service
    build:
      context: .
    ports:
      - 8080:8080
    networks:
      - spring-boot-simple
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/items"]
      interval: 10s
      timeout: 10s
      retries: 10

networks:
  spring-boot-simple:   
