global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'product_service_prometheus'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8080']